name: Merge

on:
  workflow_dispatch:
    
jobs:
  Merge_book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set Environment
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "FILE_DATE=$(date +"%Y%m%d")" >> $GITHUB_ENV
      - name: Merge
        run: |
          cd $GITHUB_WORKSPACE/Source
          cat *.json >> ALL.json
          sed -i 's/^\[//g' ALL.json
          sed -i 's/\]$//g' ALL.json
          sed -i '1i \[' ALL.json
          sed -i '$a \]' ALL.json
          sed -i 's/}\]\[{/},\n{/g' ALL.json
          mv -f ALL.json ../
      - name: Commit files
        run: |
          git config --global user.email "action@email.com"
          git config --global user.name "mergeBot"
          git commit -m "整合于${{ env.FILE_DATE }}" -a
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}